_wandb:
    value:
        cli_version: 0.23.1
        e:
            s4whnq8rak7sdvxvu0sc31aa2d2g8s2y:
                args:
                    - --epochs
                    - "120"
                    - --number_of_frames
                    - "243"
                    - --batch_size
                    - "1024"
                    - --learning_rate
                    - "0.00004"
                    - --lr_decay
                    - "0.99"
                    - --dataset
                    - h36m
                    - --keypoints
                    - cpn_ft_h36m_dbb
                    - --embed_dim
                    - "512"
                    - --depth
                    - "8"
                    - --num_heads
                    - "8"
                    - --mlp_ratio
                    - "2"
                    - --num_joints
                    - "17"
                    - --drop_rate
                    - "0.0"
                    - --attn_drop_rate
                    - "0.0"
                    - --drop_path_rate
                    - "0.0"
                    - --weight_bone
                    - "100.0"
                    - --weight_symmetry
                    - "50.0"
                    - --weight_angle
                    - "0.001"
                    - --checkpoint
                    - checkpoint/biomech_mixste_cpn_h36m
                    - --world_size
                    - "2"
                    - --master_port
                    - "8501"
                    - --master_addr
                    - 127.0.0.1
                    - --reduce_rank
                    - "0"
                    - --nolog
                    - --wandb
                codePath: main_biomech.py
                codePathLocal: main_biomech.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1178543607808"
                        used: "44345872384"
                email: sh.yangunique@gmail.com
                executable: /users/shuoyang67/miniconda/bin/python
                git:
                    commit: 7d6a5ca853b2d4a4de727c1e93fd1ee5e9c91f42
                    remote: https://github.com/sYANGunique1111/bioconstraints.git
                gpu: Quadro RTX 8000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "48318382080"
                      name: Quadro RTX 8000
                      uuid: GPU-76813b26-5542-fd4d-8bb9-1cc5906f96f8
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "48318382080"
                      name: Quadro RTX 8000
                      uuid: GPU-9064a559-a59d-b9ca-eafb-6a3560441790
                host: cetautomatix.etis-lab.fr
                memory:
                    total: "99745951744"
                os: Linux-6.8.0-63-generic-x86_64-with-glibc2.39
                program: /users/shuoyang67/projects/NewPoseProject/main_biomech.py
                python: CPython 3.10.11
                root: /users/shuoyang67/projects/NewPoseProject
                startedAt: "2026-01-16T10:29:40.961127Z"
                writerId: s4whnq8rak7sdvxvu0sc31aa2d2g8s2y
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 13
                - 16
            "4": 3.10.11
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
actions:
    value: '*'
attn_drop_rate:
    value: 0
batch_size:
    value: 1024
checkpoint:
    value: checkpoint/biomech_mixste_cpn_h36m
checkpoint_frequency:
    value: 10000
data_augmentation:
    value: true
dataset:
    value: h36m
depth:
    value: 8
drop_path_rate:
    value: 0
drop_rate:
    value: 0
embed_dim:
    value: 512
epochs:
    value: 120
evaluate:
    value: ""
keypoints:
    value: cpn_ft_h36m_dbb
learning_rate:
    value: 4e-05
lr_decay:
    value: 0.99
master_addr:
    value: 127.0.0.1
master_port:
    value: "8501"
min_loss:
    value: 100000
mlp_ratio:
    value: 2
model:
    value: mixste
nolog:
    value: true
num_heads:
    value: 8
num_joints:
    value: 17
num_workers:
    value: 4
number_of_frames:
    value: 243
patch_size:
    value: 9
reduce_rank:
    value: 0
resume:
    value: ""
subjects_test:
    value: S9,S11
subjects_train:
    value: S1,S5,S6,S7,S8
subset:
    value: 1
wandb:
    value: true
weight_angle:
    value: 0.001
weight_bone:
    value: 100
weight_symmetry:
    value: 50
world_size:
    value: 2
